### ISSUE TITLE
(400) OAuthAccessTokenException-The access_token provided does not match an approved application

### ISSUE THREAD

**Issue by abidibo** [marcopompili/django-instagram#4]
Instagram App was probably moved to sandbox mode:
https://www.instagram.com/developer/sandbox/

This causes errors:
- templatetag rendering (http://dpaste.com/1GRZYXF)
- get access token functionality

**Comment by marcopompili** [comment]
I see, I'll update as soon I'll figure out this sandbox crap.

**Comment by abidibo** [comment]
@marcopompili any news on this one? Or an idea of how much time it can take (only because I've your package used in a production deployed application)?

**Comment by marcopompili** [comment]
@abidibo I don't know, a few days ago I checked the process of submitting the app into review.

Now I have to write a privacy statement which Instagram has to review and then they "should" put the application back live. This privacy statement should inform the user about the data stored on the server and I cannot be certain which data will be stored on Django because a developer can change the code in his/her installation.

Because of this legal matter I'll probably change the application so every developer should submit their application through their Instagram account.

**Comment by ststaynov** [comment]
Does this mean that the whole app is not useable or will it work if I change the access_token?

**Comment by marcopompili** [comment]
@ststaynov It will not work if you change the access token, you also have to submit the application under review. I'm trying to find a way to avoid authentication and to completely avoid python-instagram which seems to be dead (https://github.com/facebookarchive/python-instagram)

**Comment by marcopompili** [comment]
Now this package uses scraping, so no need of python-instragram or go through Instagram review process.
